name: 'Hashnode PR Blogs'
description: 'A github action to automatically publish a blog post about the pull request on hashnode when it is merged'
author: 'aazam-gh'

# Define your inputs here.
inputs:
  hashnode-blog:
    description: 'Your hashnode blog site name'
    required: true
    default: 'blog.hashnode.dev'
  hashnode-apikey:
    description: 'Your hashnode API Key'

# Define your outputs here.
outputs:
  api-response:
    description: 'Your API output response'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'message-square'
  color: 'blue'